// pattern: Imperative Shell
// (Side-effect imports registering custom elements)

import './components/shell-window.js'
import './components/address-bar.js'
import './components/tab-bar.js'
import './components/nav-controls.js'
import './components/account-widget.js'
import './components/tile-host.js'
import './components/schema-fallback.js'
import './components/repo-page.js'
import './components/collection-page.js'
import './components/record-page.js'
import './components/tile-manager-page.js'
import './components/bookmark-bar.js'
import './components/json-viewer.js'
import './components/settings-page.js'
import './tiles/profile-tile.js'
import './tiles/post-tile.js'
import './tiles/follow-tile.js'
import './tiles/list-tile.js'
import './tiles/thread-tile.js'
import './tiles/feed-tile.js'
